### ISSUE TITLE
TODO/FIXME Count 6

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-account-http#27]
- [ ] TODO extend mocha should with this
       Commit: (2bdc2dc) Add validation and tests for all working routes.
       File:  [test/mocha/10-api.js:30](https://github.com/digitalbazaar/bedrock-account-http/blob/master/test/mocha/10-api.js#L30)
       Andrew Jones commented a year ago

  - [ ] TODO: next
       Commit: (64213dc) Add core files.
       File:  [lib/index.js:225](https://github.com/digitalbazaar/bedrock-account-http/blob/master/lib/index.js#L225)
       Dave Longley commented 2 years ago

  - [ ] TODO: improve error details
       Commit: (2bdc2dc) Add validation and tests for all working routes.
       File:  [lib/index.js:117](https://github.com/digitalbazaar/bedrock-account-http/blob/master/lib/index.js#L117)
       Andrew Jones commented a year ago

  - [ ] FIXME add an implementation in bedrock-express
       Commit: (2bdc2dc) Add validation and tests for all working routes.
       File:  [lib/index.js:92](https://github.com/digitalbazaar/bedrock-account-http/blob/master/lib/index.js#L92)
       Andrew Jones commented a year ago

  - [ ] TODO: if passport supports promises or this can be safely promisified
       Commit: (c637816) Add TODO.
       File:  [lib/index.js:71](https://github.com/digitalbazaar/bedrock-account-http/blob/master/lib/index.js#L71)
       Dave Longley commented 3 months ago

  - [ ] FIXME add an implementation in bedrock-express
       Commit: (2bdc2dc) Add validation and tests for all working routes.
       File:  [lib/index.js:17](https://github.com/digitalbazaar/bedrock-account-http/blob/master/lib/index.js#L17)
       Andrew Jones commented a year ago
